"""Add bounding box columns to DetectionResult table

Revision ID: 37530ac4cc06
Revises: 
Create Date: 2025-05-07 00:37:31.625146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37530ac4cc06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bbox_x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bbox_y', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bbox_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bbox_height', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_result', schema=None) as batch_op:
        batch_op.drop_column('bbox_height')
        batch_op.drop_column('bbox_width')
        batch_op.drop_column('bbox_y')
        batch_op.drop_column('bbox_x')

    # ### end Alembic commands ###
